---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1j5g3q6tt05njwt2d6pqzaw0lzntmw4jmvs670rf03c5s4s9tng5sl2p9ed
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1j5g3q6tt05njwt2d6pqzaw0lzntmw4jmvs670rf03c5s4s9tng5sl2p9ed
  - path_regex: terraform/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1j5g3q6tt05njwt2d6pqzaw0lzntmw4jmvs670rf03c5s4s9tng5sl2p9ed
