---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1vl08zwj2mk63jhvxz86ug7z64arqd8t36khpkxzqypcuvq4883tsdxruz4
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1vl08zwj2mk63jhvxz86ug7z64arqd8t36khpkxzqypcuvq4883tsdxruz4
  - path_regex: terraform/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1vl08zwj2mk63jhvxz86ug7z64arqd8t36khpkxzqypcuvq4883tsdxruz4
