apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ""
    api-key: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vl08zwj2mk63jhvxz86ug7z64arqd8t36khpkxzqypcuvq4883tsdxruz4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5cXZ4Z0lPNXVlbkJZd2RJ
            MFA5cEJwc1F6RFc0VU1EMmkvcEc2MVV0UkEwCmFUOTRkU01lK3NDaEFja25hOVJB
            T0VFM0JXb0ZZOFdzQnZHQ256ZExySEEKLS0tIEhMV0lMMXFLRkw3TzJnVXJVMEVw
            bS9vRzIySkZBaVNGaXcxcXJqWldzRXcKdbk+XmXUcsq84x8fpWE+eOr2LoGE1RUc
            iV4RHr+/sz0T7NpXFJTfwmUzZjVYNbE8U/2TC+AdVdwSjVT/cdzaMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-19T07:07:27Z"
    mac: ENC[AES256_GCM,data:Itk5CQHHef6l6eUPTaCZ/4T/tykns8sDCfj4IDs4YrmBovh2C9SrCPsb+H4ZFVbCBiZ3r4tqDLgJBxr3ZmE8sXoVtEd1pNL4GGbN0j0xZbEtug/TPRz0vtU3rG5QO1DJp3zpHHLuKaGrxlZmyAqltlPuKinSAsmOeYQZjrrpMDU=,iv:Zw5dCMFJzBTmYx79OKSiBGWF7Dyf/NOXys4b5Qm9kR4=,tag:TExla4NqMowjaA2sEcb7vw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
