apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ""
    SECRET_CLOUDFLARE_EMAIL: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vl08zwj2mk63jhvxz86ug7z64arqd8t36khpkxzqypcuvq4883tsdxruz4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ZHBDZjZ3bGhneHBYR2xm
            V0RJYnRMcWt2OURMeU9HeUs1TVdiYUZPTVJzCnBkTVE1NFZjVlV5OThSZjgyb09I
            alJHcXIxSGVuc3d4NTF0M3NnZStpRVUKLS0tIEZONFh0WXZIMUdiVDlUSG5xMFUw
            dEcwckM5d3ZUSXRLaVlkRE9LQU12UWMK7ZamZY5QHxsl+dR5t9unXt3+9pyPDDYb
            RJecrcCngRzg/a+uOPZtQg/fzp+9O6IibqJQ8vS/MTx5KyIa2Y3i7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-19T07:07:27Z"
    mac: ENC[AES256_GCM,data:8hxSq0veyAmsaeVeB93E23UPpo3PD7ZqVIOVGYaZvVkuFgf6oEWvpK82KtJQ0C0nbsdn4MjKIjgMucsuxs0/BvXAHWijz8LsU4pB6r3bmyaScbYp7OerLqYAQwjtyWDxmfTM0FFNmMEuHBagk38YHBz9u/NbzxKL/vE/Gwnd0Fw=,iv:/qrLGPdmOFCAQb0F2cihAnhd0dHgxV/7FSsSgmLcQpA=,tag:jV1CmnmuED7693xgZ72VPQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
